import type { HomepageDocument } from "./types";

export const homepageEn = {
  locale: "en",
  blocks: [
    {
      type: "announcement",
      props: {
        message: "Built around demonstrated capability, not just a résumé.",
        linkLabel: "See how it works",
        linkHref: "#how-it-works",
      },
    },
    {
      type: "navigation",
      props: {
        links: [
          { label: "How it works", href: "#how-it-works" },
          { label: "For talent", href: "#for-talent" },
          { label: "For organizations", href: "#for-organizations" },
          { label: "Capability passport", href: "#capability-passport" },
        ],
        loginLabel: "Log in",
        startLabel: "Get started",
        homeLabel: "HCIL home",
        talentLabel: "Talent",
        organizationLabel: "Organization",
        localeLabel: "Choose language",
      },
    },
    {
      type: "hero",
      props: {
        eyebrow: "HUMAN CAPITAL, PUT TO WORK",
        titleBefore: "Good work starts with",
        titleAccent: "what you can do.",
        description: "HCIL connects real work to proven capabilities. Break projects into clear deliverables, bring the right people together, and reward accepted work—not just job titles.",
        talentCta: "Show what you can do",
        organizationCta: "I have work to get done",
        proofTitle: "Skills with evidence.",
        proofBody: "Work with clear outcomes. A profile that grows with you.",
        previewAriaLabel: "Illustrative work package preview",
        previewLabel: "EXAMPLE WORK PACKAGE",
        categoryLabel: "BUSINESS OPERATIONS",
        workTitle: "Sales data to clear decisions",
        workDescription: "Clean a dataset, identify trends, and deliver a dashboard the team can use.",
        timelineLabel: "Timeline",
        timelineValue: "5 days",
        packagesLabel: "Work units",
        packagesValue: "3 deliverables",
        teamLabel: "Team",
        teamValue: "2–3 people",
        breakdownLabel: "THE WORK, DECOMPOSED",
        budgetLabel: "Illustrative budget",
        workUnits: [
          { number: "01", title: "Clean the sales data", capability: "Excel · Data cleaning", amount: "$80", tone: "green" },
          { number: "02", title: "Find useful patterns", capability: "Analysis · Business reasoning", amount: "$120", tone: "red" },
          { number: "03", title: "Build the dashboard", capability: "Visualisation · Reporting", amount: "$100", tone: "yellow" },
        ],
        footerNote: "Each deliverable has its own owner and acceptance criteria.",
        floatingTitle: "Capability first",
        floatingBody: "Not a one-size-fits-all score",
        floatingSecondTitle: "Milestone by milestone",
        floatingSecondBody: "Progress you can verify",
        caption: "A new way to organize work",
      },
    },
    {
      type: "principles",
      props: {
        ariaLabel: "HCIL principles",
        intro: "A better way to work together",
        items: [
          { number: "01", label: "Prove capability" },
          { number: "02", label: "Define the outcome" },
          { number: "03", label: "Share the work" },
          { number: "04", label: "Measure what matters" },
        ],
      },
    },
    {
      type: "work_model",
      props: {
        eyebrow: "A DIFFERENT WORK MODEL",
        titleBefore: "People aren't job titles.",
        titleAccent: "Work isn't one big task.",
        description: "Some people can clean data. Others can analyse it. Others can turn it into a story. HCIL helps those capabilities come together around a measurable outcome.",
        steps: [
          { index: "01 / DEFINE", title: "Start with the work", description: "Describe the outcome you need. Break it into packages with clear requirements, deadlines and acceptance criteria.", graphic: "define" },
          { index: "02 / VERIFY", title: "Match proven capability", description: "Look beyond broad labels. Use practical evidence, language requirements and the specific needs of the task.", graphic: "verify", tags: ["Data cleaning", "French writing", "Reporting"] },
          { index: "03 / DELIVER", title: "Bring the right people together", description: "One person or a small team. Each contributor owns a defined deliverable, and accepted work creates a clear record.", graphic: "deliver" },
        ],
      },
    },
    {
      type: "audience_panels",
      props: {
        talent: {
          eyebrow: "FOR TALENT",
          titleBefore: "Show your ability.",
          titleAccent: "Grow through real work.",
          description: "Your degree, experience and training matter. So does what you can demonstrate today. Build a professional record that grows as you learn, deliver and improve.",
          benefits: ["Prove individual capabilities with evidence", "Contribute where your strengths fit", "Build a history of accepted work"],
          cta: "Create your talent profile",
        },
        organization: {
          eyebrow: "FOR ORGANIZATIONS",
          titleBefore: "Describe the outcome.",
          titleAccent: "Build the right team.",
          description: "Turn a broad request into clear work packages. See which capabilities are required, assign ownership, and assess delivery against agreed criteria.",
          benefits: ["Define work before selecting talent", "Combine complementary capabilities", "Track delivery, quality and acceptance"],
          cta: "Start with a work request",
        },
      },
    },
    {
      type: "capability_passport",
      props: {
        eyebrow: "CAPABILITY, WITH CONTEXT",
        titleBefore: "A profile should show",
        titleAccent: "what backs it up.",
        description: "HCIL treats capabilities as specific, evidence-backed strengths—not a single score that attempts to describe a whole person.",
        tags: ["Data cleaning", "Financial reporting", "Customer support", "French ↔ English", "Web development", "Research & analysis"],
        cta: "Build your capability record",
        passportLabel: "HCIL / CAPABILITY PASSPORT",
        evidenceLabel: "EVIDENCE-LED",
        sampleLabel: "SAMPLE PROFILE",
        sampleName: "Alex M.",
        sampleRole: "Data & business operations",
        capabilityColumn: "CAPABILITY",
        levelColumn: "DEMONSTRATED LEVEL",
        skills: [
          { name: "Data cleaning", evidence: "Project evidence · updated recently", level: "Advanced", tone: "advanced" },
          { name: "Excel formulas", evidence: "Practical assessment", level: "Proficient", tone: "proficient" },
          { name: "Business reporting", evidence: "Accepted deliverable", level: "Developing", tone: "building" },
        ],
        permissionNote: "Evidence can be reviewed with permission.",
        disclaimer: "Illustrative interface · verification and sharing controls are planned features",
      },
    },
    {
      type: "closing_cta",
      props: {
        eyebrow: "THE HCIL APPROACH",
        titleBefore: "Make capability visible.",
        titleAccent: "Make good work possible.",
        description: "Start with what needs to be done, who can prove they can do it, and what a successful outcome looks like.",
        talentCta: "Join as talent",
        organizationCta: "I'm hiring",
      },
    },
    {
      type: "footer",
      props: {
        tagline: "Human capability, connected to meaningful work.",
        links: [
          { label: "How it works", href: "#how-it-works" },
          { label: "For talent", href: "#for-talent" },
          { label: "For organizations", href: "#for-organizations" },
          { label: "Log in", href: "/login" },
        ],
        copyrightBrand: "HCIL",
      },
    },
  ],
} satisfies HomepageDocument;
