import type { HomepageDocument } from "./types";

export const homepageFr = {
  locale: "fr",
  blocks: [
    {
      type: "announcement",
      props: {
        message: "Fondé sur les compétences démontrées, pas seulement sur le CV.",
        linkLabel: "Découvrir le fonctionnement",
        linkHref: "#how-it-works",
      },
    },
    {
      type: "navigation",
      props: {
        links: [
          { label: "Comment ça marche", href: "#how-it-works" },
          { label: "Pour les talents", href: "#for-talent" },
          { label: "Pour les organisations", href: "#for-organizations" },
          { label: "Passeport de compétences", href: "#capability-passport" },
        ],
        loginLabel: "Se connecter",
        startLabel: "Commencer",
        homeLabel: "Accueil HCIL",
        talentLabel: "Talent",
        organizationLabel: "Organisation",
        localeLabel: "Choisir la langue",
      },
    },
    {
      type: "hero",
      props: {
        eyebrow: "LE CAPITAL HUMAIN EN ACTION",
        titleBefore: "Le bon travail commence par",
        titleAccent: "ce que vous savez faire.",
        description: "HCIL relie les besoins réels aux compétences démontrées. Les projets sont découpés en livrables clairs, les bonnes personnes sont réunies et le paiement suit le travail accepté — pas seulement les intitulés de poste.",
        talentCta: "Montrez vos compétences",
        organizationCta: "J’ai du travail à faire",
        proofTitle: "Des compétences prouvées.",
        proofBody: "Des résultats clairs. Un profil qui évolue avec vous.",
        previewAriaLabel: "Aperçu illustratif d’un lot de travail",
        previewLabel: "EXEMPLE DE LOT DE TRAVAIL",
        categoryLabel: "OPÉRATIONS COMMERCIALES",
        workTitle: "Des données commerciales aux décisions",
        workDescription: "Nettoyer un jeu de données, repérer les tendances et livrer un tableau de bord exploitable.",
        timelineLabel: "Délai",
        timelineValue: "5 jours",
        packagesLabel: "Unités de travail",
        packagesValue: "3 livrables",
        teamLabel: "Équipe",
        teamValue: "2 à 3 personnes",
        breakdownLabel: "LE TRAVAIL, DÉCOMPOSÉ",
        budgetLabel: "Budget indicatif",
        workUnits: [
          { number: "01", title: "Nettoyer les données de vente", capability: "Excel · Nettoyage des données", amount: "80 $", tone: "green" },
          { number: "02", title: "Identifier les tendances", capability: "Analyse · Raisonnement métier", amount: "120 $", tone: "red" },
          { number: "03", title: "Créer le tableau de bord", capability: "Visualisation · Rapports", amount: "100 $", tone: "yellow" },
        ],
        footerNote: "Chaque livrable a son responsable et ses critères d’acceptation.",
        floatingTitle: "La compétence d’abord",
        floatingBody: "Pas de score universel",
        floatingSecondTitle: "Étape par étape",
        floatingSecondBody: "Une progression vérifiable",
        caption: "Une autre façon d’organiser le travail",
      },
    },
    {
      type: "principles",
      props: {
        ariaLabel: "Principes HCIL",
        intro: "Une meilleure façon de travailler ensemble",
        items: [
          { number: "01", label: "Prouver ses compétences" },
          { number: "02", label: "Définir le résultat" },
          { number: "03", label: "Répartir le travail" },
          { number: "04", label: "Mesurer l’essentiel" },
        ],
      },
    },
    {
      type: "work_model",
      props: {
        eyebrow: "UNE AUTRE ORGANISATION DU TRAVAIL",
        titleBefore: "Une personne n’est pas un intitulé.",
        titleAccent: "Un projet n’est pas une tâche unique.",
        description: "Certaines personnes nettoient les données, d’autres les analysent, d’autres encore en tirent un récit clair. HCIL rassemble ces compétences autour d’un résultat mesurable.",
        steps: [
          { index: "01 / DÉFINIR", title: "Partir du travail", description: "Décrivez le résultat attendu. Découpez-le en lots avec des exigences, des délais et des critères d’acceptation clairs.", graphic: "define" },
          { index: "02 / VÉRIFIER", title: "Associer des compétences prouvées", description: "Allez au-delà des intitulés généraux. Utilisez des preuves pratiques, les exigences linguistiques et les besoins réels de la tâche.", graphic: "verify", tags: ["Nettoyage des données", "Rédaction en français", "Rapports"] },
          { index: "03 / LIVRER", title: "Réunir les bonnes personnes", description: "Une personne ou une petite équipe. Chacun est responsable d’un livrable défini et le travail accepté laisse une trace vérifiable.", graphic: "deliver" },
        ],
      },
    },
    {
      type: "audience_panels",
      props: {
        talent: {
          eyebrow: "POUR LES TALENTS",
          titleBefore: "Montrez votre savoir-faire.",
          titleAccent: "Progressez grâce au travail réel.",
          description: "Votre diplôme, votre expérience et votre formation comptent. Ce que vous pouvez démontrer aujourd’hui compte aussi. Construisez un parcours professionnel qui évolue avec vos apprentissages et vos réalisations.",
          benefits: ["Prouvez vos compétences avec des éléments concrets", "Contribuez là où vos forces sont utiles", "Constituez un historique de travaux acceptés"],
          cta: "Créer mon profil talent",
        },
        organization: {
          eyebrow: "POUR LES ORGANISATIONS",
          titleBefore: "Décrivez le résultat.",
          titleAccent: "Constituez la bonne équipe.",
          description: "Transformez un besoin général en lots de travail clairs. Identifiez les compétences requises, attribuez les responsabilités et évaluez les livrables selon des critères convenus.",
          benefits: ["Définir le travail avant de choisir les talents", "Combiner des compétences complémentaires", "Suivre la livraison, la qualité et l’acceptation"],
          cta: "Décrire un besoin de travail",
        },
      },
    },
    {
      type: "capability_passport",
      props: {
        eyebrow: "LES COMPÉTENCES EN CONTEXTE",
        titleBefore: "Un profil doit montrer",
        titleAccent: "ce qui le justifie.",
        description: "HCIL présente des compétences précises appuyées par des preuves, et non une note unique prétendant résumer une personne entière.",
        tags: ["Nettoyage des données", "Rapports financiers", "Service client", "Français ↔ anglais", "Développement web", "Recherche et analyse"],
        cta: "Construire mon dossier de compétences",
        passportLabel: "HCIL / PASSEPORT DE COMPÉTENCES",
        evidenceLabel: "FONDÉ SUR DES PREUVES",
        sampleLabel: "PROFIL EXEMPLE",
        sampleName: "Alex M.",
        sampleRole: "Données et opérations commerciales",
        capabilityColumn: "COMPÉTENCE",
        levelColumn: "NIVEAU DÉMONTRÉ",
        skills: [
          { name: "Nettoyage des données", evidence: "Preuve de projet · mise à jour récente", level: "Avancé", tone: "advanced" },
          { name: "Formules Excel", evidence: "Évaluation pratique", level: "Opérationnel", tone: "proficient" },
          { name: "Rapports métier", evidence: "Livrable accepté", level: "En progression", tone: "building" },
        ],
        permissionNote: "Les preuves sont consultables avec autorisation.",
        disclaimer: "Interface illustrative · vérification et partage prévus",
      },
    },
    {
      type: "closing_cta",
      props: {
        eyebrow: "L’APPROCHE HCIL",
        titleBefore: "Rendons les compétences visibles.",
        titleAccent: "Rendons le bon travail possible.",
        description: "Partons du travail à accomplir, des personnes capables de le démontrer et de la définition d’un résultat réussi.",
        talentCta: "Rejoindre comme talent",
        organizationCta: "Je recrute",
      },
    },
    {
      type: "footer",
      props: {
        tagline: "Les compétences humaines au service d’un travail utile.",
        links: [
          { label: "Comment ça marche", href: "#how-it-works" },
          { label: "Pour les talents", href: "#for-talent" },
          { label: "Pour les organisations", href: "#for-organizations" },
          { label: "Se connecter", href: "/login" },
        ],
        copyrightBrand: "HCIL",
      },
    },
  ],
} satisfies HomepageDocument;
